apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: metrics-consumer
type: Opaque
stringData:
  RABBITMQ_USERNAME: "foo"
  RABBITMQ_PASSWORD: "bar"
  RABBITMQ_HOST: "rabbitmq-service.rabbitmq.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "metrics"
